@hostname = http://localhost:3000

// Get all contacts
# @name getAllContacts
GET {{hostname}}/contacts/

###

// Get a single contact by ID
# @name getContactById
GET {{hostname}}/contacts/{{getAllContacts.response.body.$[0]._id}}

###

// Create a new contact
# @name createContact
POST {{hostname}}/contacts
Content-Type: application/json

{
  "firstName": "Judy",
  "lastName": "Doe",
  "email": "judy.doe@example.com",
  "favoriteColor": "green",
  "birthday": "1996-06-03"
}

###

// Get the contact that was just created
# @name getCreatedContactById
GET {{hostname}}/contacts/{{createContact.response.body._id}}

###

// Update the contact that was just created by ID
# @name updateContact
PUT {{hostname}}/contacts/{{getCreatedContactById.response.body._id}}
Content-Type: application/json

{
  "firstName": "Judy",
  "lastName": "Doe [Updated]",
  "email": "judy.doe@example.com",
  "favoriteColor": "green",
  "birthday": "1996-06-03"
}

###

// Delete the contact that was just created by ID
# @name deleteContact
DELETE {{hostname}}/contacts/{{getCreatedContactById.response.body._id}}

###